apt-run: &apt-install
  name: Install Linux dependecies via apt.
  command: |
    apt-get update
    apt-get -y install elementary-sdk meson ninja git openssh-client

# TODO(bugabinga): Just building is a little useless. The build step should
# capture some output release thing and push it to GH releases.

# Here are some ideas, that could be achieved in here:
# [ ] flatpak to flathub
# [x] unit tests
# [ ] integ tests
# [ ] build documentation
# [ ] build GH landing page

version: 2
jobs:
  build_eos_stable:
    docker:
      - image: elementary/docker:loki
    steps:
      - checkout
      - run: *apt-install
      - run:
          name: Make build directory.
          command: mkdir build
      - run:
          name: Build with meson + ninja.
          command: meson build && ninja -C build
  build_eos_unstable:
    docker:
      - image: elementary/docker:loki-unstable
    steps:
      - checkout
      - run: *apt-install
      - run:
          name: Make build directory.
          command: mkdir build
      - run:
          name: Build with meson + ninja.
          command: meson build && ninja -C build
  test_eos_stable:
    docker:
      - image: elementary/docker:loki
    steps:
      - checkout
      - run: *apt-install
      - run:
          name: Make build directory.
          command: mkdir build
      - run:
          name: Build with meson + ninja.
          command: meson build && ninja -C test
      - store_artifacts:
          path: build/meson-logs/testlog.txt
          prefix: tests
  test_eos_unstable:
    docker:
      - image: elementary/docker:loki-unstable
    steps:
      - checkout
      - run: *apt-install
      - run:
          name: Make build directory.
          command: mkdir build
      - run:
          name: Build with meson + ninja.
          command: meson build && ninja -C test
      - store_artifacts:
          path: build/meson-logs/testlog.txt
          prefix: tests
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_eos_stable
      - test_eos_stable
      - build_eos_unstable
      - test_eos_unstable
